### ISSUE TITLE
Upgrade browserify

### ISSUE THREAD

**Issue by ben-ng** [atomify/atomify-js#51]
We should upgrade to 9.0.3 to get this fix - https://github.com/substack/watchify/issues/143

Which is making ribcage preview quite painful to use right now.

This is also a good time to do a minifyify update for node 0.12 compat.

**Comment by joeybaker** [comment]
Waiting on jadeify to update before we can land the browserify upgrade.

**Comment by ben-ng** [comment]
Jadeify is already ready, its locked to < 9.

**Comment by joeybaker** [comment]
Right, so it won't allow browserify v9 to be a peerDep. :)

**Comment by ben-ng** [comment]
is it friday yet?

**Comment by joeybaker** [comment]
:)
