### ISSUE TITLE
make jadeify and brfs optional

### ISSUE THREAD

**Issue by borisirota** [atomify/atomify-js#53]
Hey,

I'm using inline jade transform ([browserify-plain-jade](https://www.npmjs.com/package/browserify-plain-jade)) and there is a conflict with the default jadeify transform. In addition, I have a conflict with brfs transform.

Currently, I have a postinstall hook that updates the file and removes these transforms but it will be great to have it part of the api (I'm using atomify from the command line).

Thanks

**Comment by joeybaker** [comment]
I would support turning off all the default transforms with a flag. @ben-ng @bclinkinbeard @Techwraith thoughts?

**Comment by bclinkinbeard** [comment]
No objection here

**Comment by borisirota** [comment]
Sounds great as long as it doesn't include resrcify (should be always turned on) :)

Great project guys :+1:  :+1:  :+1:
